import { Component, ChangeDetectorRef, OnDestroy } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-upload-resume',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './upload-resume.component.html',
  styleUrls: ['./upload-resume.component.css']
})
export class UploadResumeComponent implements OnDestroy {
  selectedFile: File | null = null;
  jobDescription: string = '';
  result: any = null;
  loading = false;

  loadStep = 0;
  loadProgress = 0;
  animatedScore = 0;

  private loadInterval: any;
  private scoreInterval: any;

  constructor(private http: HttpClient, private cdr: ChangeDetectorRef) {}

  ngOnDestroy() { this.clearIntervals(); }

  private clearIntervals() {
    if (this.loadInterval) clearInterval(this.loadInterval);
    if (this.scoreInterval) clearInterval(this.scoreInterval);
  }

  onFileSelected(event: any) {
    this.selectedFile = event.target.files[0];
    this.cdr.detectChanges();
  }

  onDrop(event: DragEvent) {
    event.preventDefault();
    const file = event.dataTransfer?.files[0];
    if (file && file.type === 'application/pdf') {
      this.selectedFile = file;
      this.cdr.detectChanges();
    }
  }

  analyzeResume() {
    if (!this.selectedFile || !this.jobDescription) return;

    this.loading = true;
    this.result = null;
    this.loadStep = 0;
    this.loadProgress = 0;
    this.cdr.detectChanges();

    this.startLoadingAnimation();

    const formData = new FormData();
    formData.append('file', this.selectedFile);
    formData.append('jobDescription', this.jobDescription);

    this.http.post('http://localhost:8080/api/resume/analyze', formData).subscribe({
      next: (res: any) => {
        this.clearIntervals();
        this.loadProgress = 100;
        this.loadStep = 4;
        this.cdr.detectChanges();

        setTimeout(() => {
          this.loading = false;
          this.result = res;
          this.animatedScore = 0;
          this.cdr.detectChanges();
          setTimeout(() => this.animateScore(res.atsScore || 0), 300);
        }, 600);
      },
      error: (err) => {
        console.error('❌ Error:', err);
        this.clearIntervals();
        this.loading = false;
        this.cdr.detectChanges();
        alert('Backend error! Check if server is running.');
      }
    });
  }

  private startLoadingAnimation() {
    const steps = [
      { step: 1, progress: 20, delay: 400 },
      { step: 2, progress: 45, delay: 1200 },
      { step: 3, progress: 70, delay: 2200 },
      { step: 4, progress: 90, delay: 3500 },
    ];
    steps.forEach(({ step, progress, delay }) => {
      setTimeout(() => {
        if (this.loading) {
          this.loadStep = step;
          this.loadProgress = progress;
          this.cdr.detectChanges();
        }
      }, delay);
    });
  }

  private animateScore(target: number) {
    const steps = 60;
    const increment = target / steps;
    let current = 0;
    this.scoreInterval = setInterval(() => {
      current += increment;
      if (current >= target) {
        this.animatedScore = target;
        clearInterval(this.scoreInterval);
      } else {
        this.animatedScore = Math.floor(current);
      }
      this.cdr.detectChanges();
    }, 1500 / steps);
  }

  // ✅ PDF Download
  downloadPDF() {
    if (!this.result) return;

    const content = `
ATS RESUME ANALYSIS REPORT
===========================
Generated by ATSScan | AI-Powered Resume Intelligence

ATS SCORE: ${this.result.atsScore}% (${this.getGrade(this.result.atsScore)})

SECTION SCORES:
- Skills:     ${this.result.skillsScore || 0}%
- Experience: ${this.result.experienceScore || 0}%
- Education:  ${this.result.educationScore || 0}%

OVERALL RECOMMENDATION:
${this.result.overallRecommendation}

STRONG MATCHES:
${this.result.strongMatches?.join(', ') || 'None found'}

MISSING KEYWORDS:
${this.result.missingKeywords || 'None - Great job!'}

IMPROVEMENT SUGGESTIONS:
${this.result.suggestions?.map((s: string, i: number) => `${i + 1}. ${s}`).join('\n') || 'None'}

FORMAT ISSUES:
${this.result.formatIssues || 'No format issues found'}

---
Generated on: ${new Date().toLocaleString()}
ATSScan - AI-Powered Resume Intelligence
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ATS_Analysis_Report.txt';
    a.click();
    window.URL.revokeObjectURL(url);
  }

  getScoreColor(score: number): string {
    if (!score) return '#64748b';
    if (score >= 80) return '#22c55e';
    if (score >= 60) return '#f59e0b';
    return '#ef4444';
  }

  getStrokeDashOffset(score: number): number {
    return 314 - (score / 100) * 314;
  }

  getGrade(score: number): string {
    if (!score) return '-';
    if (score >= 90) return 'Excellent';
    if (score >= 80) return 'Great';
    if (score >= 60) return 'Average';
    return 'Needs Work';
  }

  getScoreMessage(score: number): string {
    if (!score) return '';
    if (score >= 80) return '🎉 Strong match! Apply with confidence.';
    if (score >= 60) return '📈 Good start. A few improvements needed.';
    return '⚠️ Significant gaps found. Optimize your resume.';
  }

  isArray(value: any): boolean { return Array.isArray(value); }

  splitKeywords(value: string): string[] {
    if (!value) return [];
    return value.split(',').map(k => k.trim()).filter(k => k.length > 0);
  }

  resetForm() {
    this.clearIntervals();
    this.selectedFile = null;
    this.jobDescription = '';
    this.result = null;
    this.loading = false;
    this.loadStep = 0;
    this.loadProgress = 0;
    this.animatedScore = 0;
    this.cdr.detectChanges();
  }
}